{{ if eq .Values.rbac.enabled true }}
  {{- toYaml .Values.rbac.details }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pubsub
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: {{ tpl .Values.imagePullSecretsName . }}
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pubsub.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pubsub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pubsub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | trim | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | trim | nindent 8 }}
        {{- end }}
    spec:
  {{- if eq .Values.rbac.enabled true }}
      serviceAccountName: pubsub
  {{- end }}
      containers:
        - name: pubsub-server
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AWS_REGION
            value: {{ .Values.service.aws_region }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: internal
              containerPort: {{ .Values.internal.port }}
              protocol: TCP
          args: [
              "--logging.level={{ .Values.service.logging_level }}",
              "--internal.port={{ .Values.internal.port }}",
              "--server.port={{ .Values.service.port }}"
            ]
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.internal.port }}
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.internal.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "pubsub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
