// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmployeeInfo struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeInfo) Reset()         { *m = EmployeeInfo{} }
func (m *EmployeeInfo) String() string { return proto.CompactTextString(m) }
func (*EmployeeInfo) ProtoMessage()    {}
func (*EmployeeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_cbe5ed8dfbafa8ec, []int{0}
}
func (m *EmployeeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeInfo.Unmarshal(m, b)
}
func (m *EmployeeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeInfo.Marshal(b, m, deterministic)
}
func (dst *EmployeeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeInfo.Merge(dst, src)
}
func (m *EmployeeInfo) XXX_Size() int {
	return xxx_messageInfo_EmployeeInfo.Size(m)
}
func (m *EmployeeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeInfo proto.InternalMessageInfo

func (m *EmployeeInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *EmployeeInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Person struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32         `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	EmployeeInfo         *EmployeeInfo `protobuf:"bytes,3,opt,name=employeeInfo,proto3" json:"employeeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_cbe5ed8dfbafa8ec, []int{1}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmployeeInfo() *EmployeeInfo {
	if m != nil {
		return m.EmployeeInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*EmployeeInfo)(nil), "main.EmployeeInfo")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_person_cbe5ed8dfbafa8ec) }

var fileDescriptor_person_cbe5ed8dfbafa8ec = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72,
	0xe0, 0xe2, 0x71, 0xcd, 0x2d, 0xc8, 0xc9, 0xaf, 0x4c, 0x4d, 0xf5, 0xcc, 0x4b, 0xcb, 0x17, 0x92,
	0xe2, 0xe2, 0xc8, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0xf3, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0x12,
	0x10, 0x8e, 0x52, 0x1a, 0x17, 0x5b, 0x00, 0xd8, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0xa8, 0x3e, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x1d, 0xa2, 0x83, 0x35, 0x08, 0xc4,
	0x14, 0x32, 0xe3, 0xe2, 0x49, 0x45, 0xb2, 0x51, 0x82, 0x19, 0x28, 0xc5, 0x6d, 0x24, 0xa4, 0x07,
	0x72, 0x8e, 0x1e, 0xb2, 0x5b, 0x82, 0x50, 0xd4, 0x25, 0xb1, 0x81, 0x9d, 0x6d, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0xe5, 0xd6, 0xee, 0xc6, 0x00, 0x00, 0x00,
}
