FROM alpine:latest

COPY bin/pubsub-pub /usr/local/bin/pubsub-pub

# Allows to verify certificates
RUN apk update --no-cache && apk add --no-cache ca-certificates

ENTRYPOINT ["/usr/local/bin/pubsub-pub"]