FROM cgr.dev/chainguard/wolfi-base:latest

COPY bin/pubsub-pub /usr/local/bin/pubsub-pub

# Allows to verify certificates
RUN apk update --no-cache && apk add --no-cache ca-certificates

RUN apk upgrade

ENTRYPOINT ["/usr/local/bin/pubsub-pub"]