apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsub
  namespace: atlas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
      - name: pubsub-server
        image: infobloxcto/atlas.pubsub:ffb26f7
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: us-east-1
        ports:
          - name: grpc
            containerPort: 8080
            protocol: TCP
        args: [
            "debug"
         ]
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub
  namespace: atlas
spec:
  ports:
    - name: grpc
      port: 80
      targetPort: 8080
  selector:
    app: pubsub
