apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsub-pub
  namespace: atlas 
spec: 
  replicas: 1 
  template:  
    metadata:
      labels:
        app: pubsub-pub
    spec: 
      containers:
      - name: pubsub-pub
        image: infobloxcto/atlas.pubsub-pub:c625301-dirty
        imagePullPolicy: Always
        env:
        ports:
          - name: grpc
            containerPort: 8081
        args: [
            # "-log",
            "debug"
         ]
