apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsub
  namespace: atlas 
spec: 
  replicas: 1 
  template: 
    metadata:
      labels:
        app: pubsub
    spec: 
      containers:
      - name: pubsub-server
        image: infobloxcto/atlas.pubsub:c18518c-dirty
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID #need to pass this as a env variable 
          value: $AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: us-east-1
        ports:
          - name: grpc
            containerPort: 80
            protocol: TCP
        args: [
            "debug"
         ]
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub
  namespace: atlas
spec:
  ports:
    - name: grpc
      port: 80
      targetPort: 80
  selector:
    app: pubsub 